# Laboratorio 5

## Problema

Dado un arreglo:
$$
v \in Z^{n}
$$
Cuyos elementos cumplen:
$$
v_{i} \in [0,9] 
$$
Se le pide encontrar los pares:
$$
(x_{p}, y_{p})
$$ 
Los pares deben cumplir lo siguiente: 
$$
x_{p} * y_{p} = k^{2}
$$
$$
x_{p} \in v
$$
$$
y_{p} \in v
$$
$$
\forall \ x_{p} = v_{i} \ \wedge \ y_{p} = v_{j} \ \Rightarrow \ i \neq j
$$  

## Ítems

1. En una celda mágica generar un archivo de nombre `encontrar_pares.c`. Dentro de este archivo codifique la función `encontrar_pares` que cumplan con lo solicitado por el problema.

2. En una celda, coloque el comando necesario para crear el *object file*.

3. En una celda, coloque el comando necesario para crear la *shared library*. 

4. Haga una función que posibilite el enlace con Python mediante el módulo `ctypes`. La función deberá tener el mismo nombre que su función en C, pero con el prefijo `ctypes_`.

5. Haga una instancia de la función del ítem anterior que tenga el sufijo `_raw`. 

6. En una celda, realice una prueba de funcionalidad con la función del ítem anterior con el arreglo `[9, 5, 4, 3, 1, 7, 2, 8]`. Use la función `zeros` del módulo `numpy` para crear los arreglos auxiliares que necesite.

7. Implemente una función de nombre `c_encontrar_pares` en Python que envuelva la instancia de la función de manera que la administración de la memoria es transparente al usuario y se devuelvan los arreglos con los valores de $x$ y $y$. Use la función `zeros` del módulo `numpy` para crear los arreglos auxiliares que necesite.

8. En una celda, realice una prueba de funcionalidad con la función del ítem anterior con el arreglo `[9, 5, 4, 3, 1, 7, 2, 8]`. 

9. Implemente en Python una función de nombre `python_encontrar_pares` que le servirá como referencia. Debe usar python crudo, es decir, no puede usar módulos, salvo la función `zeros` del módulo `numpy` para crear los arreglos auxiliares que necesite.

10. En una celda, realice una prueba de funcionalidad con la función del ítem anterior con el arreglo `[9, 5, 4, 3, 1, 7, 2, 8]`.

11. En una celda, calcule el error relativo del arreglo que contiene los valores de $x$. Use los valores calculados por la función `python_encontrar_pares` como referencia.

12. En una celda, calcule el error relativo del arreglo que contiene los valores de $y$. Use los valores calculados por la función `python_encontrar_pares` como referencia. 

13. En una celda, realice 50 mediciones de tiempo para un arreglo de `1024` elementos para sus funciones `c_encontrar_pares` y `python_encontrar_pares`. Las mediciones de tiempo de cada una de las funciones deberán estar en listas independientes.

14. En una celda, presente el código que genere una gráfica de las mediciones de tiempo realizadas para la función `python_contrar_pares` y su mediana de las mediciones. 

15. En una celda, presente el código que genere una gráfica de las mediciones de tiempo realizadas para la función `c_contrar_pares` y su mediana de las mediciones. 

16. Dados los tamaños `[32, 64, 128, 256, 512, 1024]`. Realice 50 mediciones de tiempo por cada tamaño para sus funciones `c_encontrar_pares` y `python_encontrar_pares`. Para cada tamaño considere que la medición se corresponderá con la mediana de las 50 mediciones realizadas.

17. En una celda, presente el código que genere una gráfica de "tiempo de ejecución vs tamaño" para sus funciones `c_encontrar_pares` y `python_encontrar_pares`. 

18. En una celda, presente el código que genere una gráfica de "speedup vs tamaño". Considere que está midiendo el *speedup* de la función en C, respecto de la función en Python. 

Tabla de puntos:

| ítem | puntos |
|:----:|:------:|
|   1  |   3.0  |
|   2  |   0.25 |
|   3  |   0.25 |
|   4  |   0.5  |
|   5  |   0.5  |
|   6  |   0.5  |
|   7  |   0.5  |
|   8  |   0.5  |
|   9  |   3.0  |
|  10  |   0.5  |
|  11  |   0.5  |
|  12  |   0.5  |
|  13  |   1.0  |
|  14  |   0.5  |
|  15  |   0.5  |
|  16  |   2.0  |
|  17  |   0.25 |
|  18  |   0.25 |


## Observaciones

1. Sobre la función `encontrar_pares`, tenga en cuenta lo siguiente:

* Los elementos $x_{p}$ deben estar en memoria dinámica. 
* Los elementos $y_{p}$ deben estar en memoria dinámica. 
* Los punteros a los elementos $x$ y $y$ deben ser pasados por referencia a la función `encontrar_pares`. 
* El valor de $k$ no es argumento de la función `encontrar_pares`, ni variable local. La expresión $k^{2}$  lo que significa es que el producto de $x_{p}$ y $y_{p}$ es un cuadrado perfecto.

2. Los ítems que valen menos de un punto deberán ser perfectamente funcionales para tener algún tipo de puntaje asignado.
3. Los puntajes sobre mediciones solo serán asignados bajo el supuesto de que sus funciones hacen lo esperado. 
4. En sus mediciones de error relativo considere solo los elementos con valores no nulos.
5. La presentación deberá ser un cuaderno de *jupyter* de nombre `lab5_codigoalumno` con formato `.ipynb`. No se aceptará ningún otro formato.

In [ ]:
# no borrar esta celda
! rm *.c
! rm *.o
! rm *.so

In [1]:
%%file encontrar_pares.c
#include <stdio.h>
#include <math.h>
int encontrar_pares(int *v,int N, int* xp, int* yp){
    int n=0;
    for(int i=0; i<N; i++){
        for(int j=0; j<N; j++){
            if(i != j){
                int a = (int)sqrt(v[i]*v[j]);
                if(pow(a,2) == v[i]*v[j]){
                    
                    xp[n] =v[i];
                    yp[n] =v[j];
                    n++;
                }
            }
        }
    }
    return n;
}

Overwriting encontrar_pares.c


In [7]:
! gcc -c encontrar_pares.c -o encontrar_pares.o

In [8]:
! gcc -fPIC -shared encontrar_pares.o -o encontrar_pares.so

In [9]:
import ctypes
import numpy as np
def ctypes_encontrar_pares():

    lib = ctypes.CDLL('./encontrar_pares.so')

    lib.encontrar_pares.argtypes = [
        np.ctypeslib.ndpointer(dtype = np.int32),
        ctypes.c_int,
        np.ctypeslib.ndpointer(dtype = np.int32),
        np.ctypeslib.ndpointer(dtype = np.int32),
    ]
    lib.encontrar_pares.restypes = ctypes.c_int
    return lib.encontrar_pares

In [10]:
ctypes_encontrar_pares_raw = ctypes_encontrar_pares()

In [11]:
v = np.asarray([9,5,4,3,1,7,2,8],dtype = np.int32)
N = len(v)
xp = np.zeros(N*(N-1),dtype = np.int32)
yp = np.zeros(N*(N-1),dtype = np.int32)
c_par = 0
c_par = ctypes_encontrar_pares_raw(v,N,xp,yp)

xp = np.zeros(c_par,dtype = np.int32)
yp = np.zeros(c_par,dtype = np.int32)

c_par = ctypes_encontrar_pares_raw(v,N,xp,yp)
print(c_par,xp,yp)


8 [9 9 4 4 1 1 2 8] [4 1 9 1 9 4 8 2]


In [12]:
def c_encontrar_pares(v,N):
    xp = np.zeros(N*(N-1),dtype = np.int32)
    yp = np.zeros(N*(N-1),dtype = np.int32)
    c_par = 0
    c_par = ctypes_encontrar_pares_raw(v,N,xp,yp)

    xp = np.zeros(c_par,dtype = np.int32)
    yp = np.zeros(c_par,dtype = np.int32)

    c_par = ctypes_encontrar_pares_raw(v,N,xp,yp)
    
    return c_par,xp,yp


In [13]:
v = np.asarray([9,5,4,3,1,7,2,8],dtype = np.int32)
N = len(v)
c_encontrar_pares(v,N)

(8,
 array([9, 9, 4, 4, 1, 1, 2, 8], dtype=int32),
 array([4, 1, 9, 1, 9, 4, 8, 2], dtype=int32))

In [16]:
def python_encontrar_pares(v,N):
    xp = np.zeros(N*(N-1),dtype = np.int32)
    yp = np.zeros(N*(N-1),dtype = np.int32)
    n=0
    for i in range(N):
        for j in range(i,N):
            if(i != j):
                a = (v[i]*v[j])**0.5
                if(a**2 == v[i]*v[j]):
                    n+=1

    xp = np.zeros(n,dtype = np.int32)
    yp = np.zeros(n,dtype = np.int32)
    n=0
    for i in range(N):
        for j in range(i,N):
            if(i != j):
                a = (v[i]*v[j])**0.5
                if(a**2 == v[i]*v[j]):
                    xp[n] =v[i]
                    yp[n] =v[j]
                    n+=1

    return xp,yp,n
    

In [17]:
v = np.asarray([9,5,4,3,1,7,2,8],dtype = np.int32)
N = len(v)
python_encontrar_pares(v,N)

(array([9, 9, 9, 5, 4, 3, 7, 7, 2], dtype=int32),
 array([4, 3, 1, 7, 1, 7, 2, 8, 8], dtype=int32),
 9)

In [20]:
from numpy import linalg as LA 
x_py = np.asarray([9,9,4,2]).astype(np.int32)
x_c = np.asarray([9,9,4,2]).astype(np.int32)

y_py = np.asarray([4,1,1,8]).astype(np.int32)
y_c = np.asarray([4,1,1,8]).astype(np.int32)

In [22]:
errorX = LA.norm(x_py - x_c)/ LA.norm(x_py)
print(errorX)

0.0


In [23]:
errorY= LA.norm(y_py - y_c)/ LA.norm(y_py)
print(errorY)

0.0
